# Site settings
title: Eva Ma
email: mm99@rice.edu
description: > # this means to ignore newlines until "baseurl:"
  My name is Eva Ma.
baseurl:  # the subpath of your site, e.g. /blog/
url:  https://8vama.github.io/ # the base hostname & protocol for your site
twitter_username: twitter_username
github_username:  8vama

# Build settings
markdown: kramdown

highlighter: rouge

# Pagination
paginate: 15
paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
    permalink: /portfolio/:path/
  poetry:
    output: true
    permalink: /poetry/:path/


